"""
    Makes the tables. Programming it bc the command can be brutal.

    Yes, over a thousand lines of CREATE TABLE commands...

"""
from Utils.Constants import Constants
from Utils.Basic_Utils import Basic_Utils as BU
from Utils.Database_Driver import Database_Driver

# teamInfo from Constants. Need to populate this.
create_teams = """
CREATE TABLE teams(
    season INT,
    team TEXT,
    league TEXT,
    division TEXT,
    TZ TEXT,
    full_name TEXT,
    nickname TEXT
);
"""

create_schdeules = """
CREATE TABLE schedules(
    season INT,
    team TEXT,
    game_num INT,
    date TEXT,
    link_to_days_standings TEXT,
    boxscore_link TEXT,
    home_or_vs TEXT,
    opponent TEXT,
    result TEXT,
    R INT,
    RA INT,
    innings REAL,
    record TEXT,
    rank INT,
    games_back REAL,
    winning_pitcher TEXT,
    link_to_winner TEXT,
    losing_pitcher TEXT,
    link_to_loser TEXT,
    saving_pitcher TEXT,
    link_to_savior TEXT,
    length_of_game TEXT,
    day_or_night TEXT,
    attendance INT,
    cLI REAL,
    win_loss_streak INT,
    reschedule TEXT,
    team0 INT,
    team1 INT,
    team2 INT,
    team3 INT,
    team4 INT,
    team5 INT,
    team6 INT,
    team7 INT,
    team8 INT,
    team9 INT,
    home_team_actually_away BOOL,
    team_H INT,
    team_E INT,
    team_extras INT,
    additional_innings INT,
    opp0 INT,
    opp1 INT,
    opp2 INT,
    opp3 INT,
    opp4 INT,
    opp5 INT,
    opp6 INT,
    opp7 INT,
    opp8 INT,
    opp9 INT,
    opp_H INT,
    opp_E INT,
    opp_extras INT,
    PRIMARY KEY (team, game_num, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_boxscores_batting = """
CREATE TABLE boxscores_batting(
    season INT,
    team TEXT,
    game_num TEXT,
    batter TEXT,
    link_to_player_page TEXT,
    pos TEXT,
    started INT,
    lineup_pos INT,
    AB INT,
    R INT,
    H INT,
    RBI INT,
    BB INT,
    SO INT,
    PA INT,
    BA REAL,
    OBP REAL,
    SLG REAL,
    OPS REAL,
    pitches_thrown INT,
    strikes INT,
    WPA REAL,
    aLI REAL,
    WPA_plus REAL,
    WPA_minus REAL,
    cWPA REAL,
    RE24 REAL,
    PO INT,
    A INT,
    details TEXT
);
"""

create_boxscores_pitching = """
CREATE TABLE boxscores_pitching (
    season INT,
    team TEXT,
    game_num INT,
    pitcher TEXT,
    link_to_player_page TEXT,
    IP REAL,
    H INT,
    R INT,
    ER INT,
    BB INT,
    SO INT,
    HR INT,
    ERA REAL,
    BF INT,
    pitches INT,
    strikes INT,
    strikes_by_contact INT,
    strikes_swinging INT,
    strikes_looking INT,
    ground_balls INT,
    fly_balls INT,
    lime_drives INT,
    unknown INT,
    gamescore INT,
    inherited_runners INT,
    inherited_score INT,
    WPA REAL,
    aLI REAL,
    cWPA REAL,
    acLI REAL,
    RE24 REAL
);
"""

create_play_by_play = """
CREATE TABLE play_by_play(
    season INT,
    boxscore_link TEXT,
    inning TEXT,
    count TEXT,
    out INT,
    RoB TEXT,
    pitches INT,
    pitch_count TEXT,
    pitch_sequence,
    run_or_out TEXT,
    batting_team TEXT,
    batter TEXT,
    link_to_batter TEXT,
    pitcher TEXT,
    link_to_pitcher TEXT,
    wWPA INT,
    wWE INT,
    description TEXT
);
"""

create_player_info = """
CREATE TABLE player_info(
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    nationality TEXT,
    bats TEXT,
    throws TEXT,
    height INT,
    weight INT,
    date_of_birth TEXT,
    years INT,
    G INT,
    GS INT,
    batting INT,
    defense INT,
    P INT,
    C INT,
    "1B" INT,
    "2B" INT,
    "3B" INT,
    SS INT,
    LF INT,
    CF INT,
    RF INT,
    OF INT,
    DH INT,
    PH INT,
    PR INT,
    WAR REAL,
    salary INT,
    allstart TEXT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_player_batting = """
CREATE TABLE player_batting(
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    pos TEXT,
    age INT,
    G INT,
    PA INT,
    AB INT,
    R INT,
    H INT,
    "2B" INT,
    "3B" INT,
    HR INT,
    RBI INT,
    SB INT,
    CS INT,
    BB INT,
    SO INT,
    BA REAL,
    OBP REAL,
    SLG REAL,
    OPS REAL,
    OPS_plus REAL,
    TB INT,
    GDP INT,
    HBP INT,
    SH INT,
    SF INT,
    IBB INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_player_pitching = """
CREATE TABLE player_pitching(
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    pos TEXT,
    age INT,
    W INT,
    L INT,
    W_L_percent REAL,
    ERA REAL,
    G INT,
    GS INT,
    GF INT,
    CG INT,
    SHO INT,
    SV INT,
    IP REAL,
    H INT,
    R INT,
    ER INT,
    HR INT,
    BB INT,
    IBB INT,
    SO INT,
    HBP INT,
    BK INT,
    WP INT,
    BF INT,
    ERA_plus INT,
    FIP REAL,
    WHIP REAL,
    H9 REAL,
    HR9 REAL,
    BB9 REAL,
    SO9 REAL,
    SO_PER_W REAL,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_player_fielding = """
CREATE TABLE player_fielding (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    innings REAL,
    chances INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    fielding_percentage REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rgood INT,
    RF_per_9 REAL,
    RF_per_game REAL,
    PB INT,
    WP INT,
    SB INT,
    CS INT,
    CS_percentage INT,
    pick_offs INT,
    pos_summary TEXT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_player_batter_values = """
CREATE TABLE player_batter_values (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    PA INT,
    Rbat INT,
    Rbaser INT,
    Rdp INT,
    Rfield INT,
    Rpos INT,
    RAA INT,
    WAA REAL,
    Rrep INT,
    RAR INT,
    WAR REAL,
    waaWL_percentage REAL,
    season_WL_percentage REAL,
    oWAR REAL,
    dWAR REAL,
    oRAR INT,
    salary INT,
    acquired TEXT,
    pos_summary TEXT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_player_pitcher_values = """
CREATE TABLE player_pitcher_values (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    IP REAL,
    G INT,
    GS INT,
    R INT,
    RA9 REAL,
    RA9opp REAL,
    RA9def REAL,
    RA9role REAL,
    PPFp REAL,
    RA9avg,
    RAA INT,
    WAA REAL,
    gmLI REAL,
    WAAadj REAL,
    WAR REAL,
    RAR INT,
    waaWL_percentage REAL,
    season_WL_percentage REAL,
    salary INT,
    acquired TEXT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_advanced_batting = """
CREATE TABLE player_advanced_batting (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    PA INT,
    Outs INT,
    RC INT,
    RC_per_game REAL,
    AIR INT,
    BAbip REAL,
    BA REAL,
    lgBA REAL,
    OBP REAL,
    lgOBP REAL,
    SLG REAL,
    lgSLG REAL,
    OPS REAL,
    lgOPS REAL,
    OPS_plus REAL,
    OWn_percentage REAL,
    BtRuns REAL,
    BtWins REAL,
    TotA REAL,
    SecA REAL,
    ISO REAL,
    PwrSpd REAL,
    pos_summary TEXT
);
"""

create_baserunning = """
CREATE TABLE baserunning (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    PA INT,
    ROE INT,
    SI INT,
    RS_percentage INT,
    SBO INT,
    SB INT,
    CS INT,
    SB_percentage INT,
    SB2 INT,
    CS2 INT,
    SB3 INT,
    CS3 INT,
    SBH INT,
    CSH INT,
    PO INT,
    PCS INT,
    OOB INT,
    OOB1 INT,
    OOB2 INT,
    OOB3 INT,
    OOBHm INT,
    BT INT,
    XBT_percentage INT,
    first_S INT,
    first_S2 INT,
    first_S3 INT,
    first_D INT,
    first_D3 INT,
    first_DH INT,
    second_S INT,
    second_S3 INT,
    second_SH INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_pinch_hit_home_run_situation_hitting = """
CREATE TABLE pinch_hit_home_run_situational_hitting (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    PA INT,
    Ptn_percentage REAL,
    H INT,
    Inf INT,
    Bnt INT,
    PH_AB INT,
    PH_H INT,
    PH_HR INT,
    PH_RBI INT,
    PH_PHlev REAL,
    HR INT,
    GS INT,
    GSo INT,
    HR_vRH INT,
    HR_vLH INT,
    HR_Hm INT,
    HR_Rd INT,
    HR_IP INT,
    SH_Att INT,
    SH_Suc INT,
    SH_percentage REAL,
    GIDP_Opp INT,
    GIDP_DP INT,
    GIDP_percentage REAL,
    PrdOut_Opp INT,
    PrdOut_Suc INT,
    PrdOut_percentage REAL,
    BR INT,
    BRS INT,
    BRS_percentage REAL,
    advances_less_than_two_outs_3B INT,
    advances_Scr INT,
    advances_Scr_percentage REAL,
    advances_no_outs_2B INT,
    advances_Adv INT,
    advances_Adv_percentage REAL,
    PAu INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_pitches_batting = """
CREATE TABLE pitches_batting (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    PA INT,
    Pit INT,
    Pit_per_PA REAL,
    Str INT,
    Str_percentage REAL,
    L_per_Str REAL,
    S_per_Str REAL,
    F_per_Str REAL,
    I_per_Str REAL,
    AS_per_Str REAL,
    I_per_BII REAL,
    AS_per_Pit REAL,
    Con REAL,
    first_S REAL,
    three_zero_percentage REAL,
    three_zero_counts INT,
    three_zero_s INT,
    two_zero_percenate REAL,
    two_zero_counts INT,
    two_zero_s INT,
    three_one_percentage REAL,
    three_one_counts INT,
    three_one_s INT,
    L_per_SO INT,
    S_per_SO INT,
    L_per_SO_percentage REAL,
    PAu INT,
    Pitu INT,
    Stru INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_pitching_baserunning_and_situations = """
CREATE TABLE pitching_baserunning_and_situations (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    IP REAL,
    PA INT,
    H INT,
    Inf INT,
    Bnt INT,
    HR_tot INT,
    GS INT,
    GSo INT,
    HR_vRH INT,
    HR_vLH INT,
    HR_Hm INT,
    HR_Rd INT,
    advances_less_than_two_outs_3B INT,
    advances_Scr INT,
    advances_SO INT,
    advances_Scr_percentage REAL,
    ROE INT,
    WP INT,
    PH INT,
    SBO INT,
    SB INT,
    CS INT,
    SB_percentage INT,
    SB2 INT,
    CS2 INT,
    SB3 INT,
    CS3 INT,
    SBH INT,
    CSH INT,
    PO INT,
    PCS INT,
    BT INT,
    PAu INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_pitches_pitcher = """
CREATE TABLE pitches_pitcher (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    IP INT,
    PA INT,
    Pit INT,
    Pit_per_PA REAL,
    Str INT,
    Str_percentage REAL,
    L_per_Str REAL,
    S_per_Str REAL,
    F_per_Str REAL,
    I_per_Str REAL,
    AS_per_Str REAL,
    I_per_BII REAL,
    AS_per_Pit REAL,
    Con REAL,
    first_S REAL,
    three_zero_percentage REAL,
    three_zero_counts INT,
    three_zero_s INT,
    zero_two_percenate REAL,
    zero_two_counts INT,
    zero_two_s INT,
    zero_two_h INT,
    L_per_SO INT, 
    S_per_SO INT,
    L_per_SO_percentage REAL,
    three_p_K INT,
    four_per_W INT,
    PAu INT,
    Pitu INT,
    Stru INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_totals = """
CREATE TABLE fielding_totals (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fld_percentage REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rgood INT,
    RF_per_nine REAL,
    RF_per_G REAL,
    PB INT,
    WP INT,
    SB INT,
    CS INT,
    CS_percentage INT,
    ls_CS_percentage INT,
    Pickoffs INT,
    position_summary TEXT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

# tables below are standard and advanced combined.
# repeats from fielding not included
create_fielding_catcher = """
CREATE TABLE fielding_catcher (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rctch INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    RszC INT,
    RsbC INT,
    RerC INT,
    RF_per_nine REAL,
    RF_per_game INT,
    PB INT,
    WP INT,
    SB INT,
    CS INT,
    CS_percentage INT,
    PA INT,
    pitching_ERA REAL,
    pitching_RA9 REAL,
    Fld INT,
    F20_percentage INT,
    XI INT,
    FC INT,
    PO_Tot INT,
    PO_Cgt INT,
    PO_Frc INT,
    PO_Tag INT,
    PO_SO INT,
    A_1B INT,
    A_2B INT,
    A_3B INT,
    A_K23 INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_263 INT,
    DP_n23 INT,
    DP_GB INT,
    bFld int,
    bF20_percentage INT,
    CSctch INT,
    SB2 INT,
    CS2 INT,
    SB3 INT,
    CS3 INT,
    SBH INT,
    CSH INT,
    pitkoff INT,
    PCS INT,
    PBA INT,
    RK INT,
    SBIev REAL,
    CSIev REAL,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""
create_fielding_first_base = """
CREATE TABLE fielding_first_base (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rdp INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    Rbnt INT,
    RF_per_9 REAL,
    RF_per_G REAL,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    GBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    FC INT,
    PO_Cgt INT,
    PO_Frc INT,
    PO_Tag INT,
    PO_3U INT,
    A_1B INT,
    A_2B INT,
    A_Hm INT,
    A_Rly INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_363 INT,
    DP_361 INT,
    DP_36 INT,
    DP_GB INT,
    DP_GBs INT,
    DP_LD INT,
    DP_LDs INT,
    DP_LDf INT,
    bFld INT,
    Bf2O_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_second_base = """
CREATE TABLE fielding_second_base (
season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rdp INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rdp_BIS INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    RF_per_9 REAL,
    RF_per_G REAL,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    GBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    FC INT,
    PO_Cgt INT,
    PO_Frc INT,
    PO_Tag INT,
    A_1B INT,
    A_2B INT,
    A_Hm INT,
    A_Rly INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_643 INT,
    DP_543 INT,
    DP_463 INT,
    DP_43 INT,
    DP_GB INT,
    DP_GBs INT,
    DP_GBr INT,
    DP_LD INT,
    DP_LDs INT,
    DP_LDf INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_third_base = """
CREATE TABLE fielding_third_base (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rdp INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    Rbnt INT,
    RF_per_9 REAL,
    RF_per_G REAL,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    GBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    FC INT,
    PO_Cgt INT,
    PO_Frc INT,
    PO_Tag INT,
    A_1B INT,
    A_2B INT,
    A_Hm INT,
    A_Rly INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_543 INT,
    DP_53 INT,
    DP_GB INT,
    DP_LD INT,
    DP_LDs INT,
    DP_LDf INT,
    bFld INT,
    Bf2O_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_ss = """
CREATE TABLE fielding_ss (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rdp INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rdp_BIS INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    RF_per_9 REAL,
    RF_per_G REAL,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    GBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    FC INT,
    PO_Cgt INT,
    PO_Frc INT,
    PO_Tag INT,
    A_1B INT,
    A_2B INT,
    A_Hm INT,
    A_Rly INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_643 INT,
    DP_63 INT,
    DP_463 INT,
    DP_163 INT,
    DP_363 INT,
    DP_GB INT,
    DP_GBs INT,
    DP_GBr INT,
    DP_LD INT,
    DP_LDs INT,
    DP_LDf INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_lf = """
CREATE TABLE fielding_lf (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rof INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rof_BIS INT,
    Rgood INT,
    RF_per_nine REAL,
    RF_per_game REAL,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    A_1B INT,
    A_2B INT,
    A_3B INT,
    A_Hm INT,
    single_man_on_first_opp INT,
    single_man_on_first_held INT,
    single_man_on_first_kill INT,
    single_man_on_second_opp INT,
    single_man_on_second_held INT,
    single_man_on_second_kill INT,
    double_man_on_first_opp INT,
    double_man_on_first_held INT,
    double_man_on_first_kill INT,   
    flyout_under_two_outs_man_on_third_opp INT,
    flyout_under_two_outs_man_on_third_held INT,
    flyout_under_two_outs_man_on_third_kill INT,
    flyout_under_two_outs_man_on_second_opp INT,
    flyout_under_two_outs_man_on_second_held INT,
    flyout_under_two_outs_man_on_second_kill INT,
    baserunning_totals_opp INT,
    baserunning_totals_held INT,
    baserunning_totals_held_percentage REAL,
    baserunning_totals_adv INT,
    baserunning_totals_kill INT,
    baserunning_totals_kill_percentage REAL,
    baserunning_totals_aother INT,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    FBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_cf = """
CREATE TABLE fielding_cf (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rof INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rof_BIS INT,
    Rgood INT,
    RF_per_nine REAL,
    RF_per_game REAL,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    A_1B INT,
    A_2B INT,
    A_3B INT,
    A_Hm INT,
    single_man_on_first_opp INT,
    single_man_on_first_held INT,
    single_man_on_first_kill INT,
    single_man_on_second_opp INT,
    single_man_on_second_held INT,
    single_man_on_second_kill INT,
    double_man_on_first_opp INT,
    double_man_on_first_held INT,
    double_man_on_first_kill INT,
    flyout_under_two_outs_man_on_third_opp INT,
    flyout_under_two_outs_man_on_third_held INT,
    flyout_under_two_outs_man_on_third_kill INT,
    flyout_under_two_outs_man_on_second_opp INT,
    flyout_under_two_outs_man_on_second_held INT,
    flyout_under_two_outs_man_on_second_kill INT,
    baserunning_totals_opp INT,
    baserunning_totals_held INT,
    baserunning_totals_held_percentage REAL,
    baserunning_totals_adv INT,
    baserunning_totals_kill INT,
    baserunning_totals_kill_percentage REAL,
    baserunning_totals_aother INT,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    FBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_rf = """
CREATE TABLE fielding_rf (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    Fielding_per REAL,
    Rtot INT,
    Rtot_per_year INT,
    Rtz INT,
    Rof INT,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rof_BIS INT,
    Rgood INT,
    RF_per_nine REAL,
    RF_per_game REAL,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    A_1B INT,
    A_2B INT,
    A_3B INT,
    A_Hm INT,
    single_man_on_first_opp INT,
    single_man_on_first_held INT,
    single_man_on_first_kill INT,
    single_man_on_second_opp INT,
    single_man_on_second_held INT,
    single_man_on_second_kill INT,
    double_man_on_first_opp INT,
    double_man_on_first_held INT,
    double_man_on_first_kill INT,   
    flyout_under_two_outs_man_on_third_opp INT,
    flyout_under_two_outs_man_on_third_held INT,
    flyout_under_two_outs_man_on_third_kill INT,
    flyout_under_two_outs_man_on_second_opp INT,
    flyout_under_two_outs_man_on_second_held INT,
    flyout_under_two_outs_man_on_second_kill INT,
    baserunning_totals_opp INT,
    baserunning_totals_held INT,
    baserunning_totals_held_percentage REAL,
    baserunning_totals_adv INT,
    baserunning_totals_kill INT,
    baserunning_totals_kill_percentage REAL,
    baserunning_totals_aother INT,
    PA INT,
    RHB_percentage INT,
    BIP_percentage INT,
    FBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_of = """
CREATE TABLE fielding_of (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    Rtz INT,
    Rof INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""

create_fielding_pitcher = """
CREATE TABLE fielding_pitcher (
    season INT,
    player TEXT,
    team TEXT,
    player_link TEXT,
    age INT,
    G INT,
    GS INT,
    CG INT,
    Inn REAL,
    Ch INT,
    PO INT,
    A INT,
    E INT,
    DP INT,
    fielding_percentage REAL,
    Rdrs INT,
    Rdrs_per_year INT,
    Rpm INT,
    Rgood INT,
    Rair INT,
    Rrange INT,
    Rthrow INT,
    RsbP INT,
    RF_per_nine REAL,
    RF_per_game REAL,
    SB INT,
    CS INT,
    CS_percentage INT,
    Pickoff INT,
    PA INT,
    BIP_percentage INT,
    GBIP_percentage INT,
    Fld INT,
    F2O_percentage INT,
    FC INT,
    PO_Cgt INT,
    PO_31 INT,
    A_1B INT,
    A_2B INT,
    E_Cch INT,
    E_Fld INT,
    E_Thr INT,
    E_ROE INT,
    DP_163 INT,
    DP_GB INT,
    DP_LD INT,
    bFld INT,
    bF20_percentage INT,
    PRIMARY KEY (team, player_link, season),
    FOREIGN KEY (team) REFERENCES teams (team)
);
"""


def main():

    commands = [
        "create_teams",
        "create_schdeules",
        "create_boxscores_batting",
        "create_boxscores_pitching",
        "create_play_by_play",
        "create_player_info",
        "create_player_batting",
        "create_player_pitching",
        "create_player_fielding",
        "create_player_batter_values",
        "create_player_pitcher_values",
        "create_advanced_batting",
        "create_baserunning",
        "create_pinch_hit_home_run_situation_hitting",
        "create_pitches_batting",
        "create_pitching_baserunning_and_situations",
        "create_pitches_pitcher",
        "create_fielding_totals",
        "create_fielding_catcher",
        "create_fielding_first_base",
        "create_fielding_second_base",
        "create_fielding_third_base",
        "create_fielding_ss",
        "create_fielding_lf",
        "create_fielding_cf",
        "create_fielding_of",
        "create_fielding_rf",
        "create_fielding_pitcher",
    ]

    db = Database_Driver("baseball.db")

    count = 1
    for command in commands:
        db.execute_insert(eval(command))
        BU.printProgressBar(count, len(commands),
                            prefix="Creating Tables...",
                            length=30)
        count += 1

main()
